### ISSUE TITLE
Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by evenchange4** [wuct/react-dom-utils#11]
```
Uncaught TypeError: Cannot read property 'removeEventListener' of undefined
```

The confusing error message above occurred when I was developing some features in my project.
I think this kind of HOC function may cause error handing problem and get blocked. 🤕

<img width="1280" alt="2016-04-25 21 37 46" src="https://cloud.githubusercontent.com/assets/1527371/14785923/6b65757e-0b2f-11e6-9771-a2541d35827c.png">

**Comment by wuct** [comment]
Could you provide your `getTarget` function which is the first argument of `mapPropsOnEvent`? In the mean time, I will add some tests for `mapPropsOnEvent`.

**Comment by wuct** [comment]
@evenchange4 do you mind to check #13 covering your use case?

**Comment by evenchange4** [comment]
Here is my case

```js
  mapPropsOnEvent(
    () => window,
    'scroll',
    (e, { state }) => {
      const scrollTop = window.scrollY;

      return {
        scrollTop,
        isSubHeaderShow: scrollTop === 0 || state.scrollTop > scrollTop,
      };
    },
    throttle,
    false,
  ),
```

**Comment by evenchange4** [comment]
Remind: [react-overlays'](https://github.com/react-bootstrap/react-overlays) `Protal` component might cause this issue.
