### ISSUE TITLE
Update peerDependencies

### ISSUE THREAD

**Issue by wuct** [wuct/react-dom-utils#32]
Update `react` and `recompose` version in peerDeps

**Comment by vyorkin** [comment]
I think its possible to update recompose to `0.21.0`

**Comment by wuct** [comment]
@vyorkin Yap, you are right. I am going to release a new version that update recompose.

**Comment by wuct** [comment]
Landed in 2.0.1

**Comment by vyorkin** [comment]
cool, thanks!
